### PR TITLE
Initial draft of the Senior Engineer skills list

### PR DESCRIPTION
**Pull request by rbanks54**
Some thinking behind the wording

1. Describing the SE role in a way that matches the high level description and radar chart [on the intranet](https://readify.sharepoint.com/the-way-we-work/Pages/Consulting%20Roles.aspx)
1. Make sure the SE is defined as a "best of the best" role within Readify, with a technical focus. Our elite Special Forces members who embody all that Readify stands for, but who don't want to head down a team leadership path.
1. Avoid defining a tech/soluton architect role or restating the old psuedo-role of Tech Specialist, even though the TS skills are a central part of this new SE role.
1. Make it clear that the SE role needs awesome soft skills, and differentiate it enough from an SD role so that people don't expect a promotion to SE simply because they've been in the SD role for a while and are pretty good at just coding.
1. Indicate that an SE needs much deeper & broader skills and knowledge than an SD does, as well as having a specialisation. This will ensure we don't have SEs who are awesome at one thing, and only one thing, and can't really contribute anywhere else. We still need to be able to sell these people into gigs outside their deep specialisation.

So have a look, see what's been missed and where the wording is a little too vague.

The flood gates are open! :-)

### CODE REVIEW

**Comment by robdmoore** [comment]
What if you are a very very good generalist?

**Comment by aaronpowell** [comment]
Isn't the point of the role that your a Senior Engineer _Some Tech_, and it's not a generalist role?

**Comment by robdmoore** [comment]
I think you should be able to become a SE if you are an incredibly skilled generalist, Michelle also confirmed to me yesterday that generalists should be able to become a SE, she also suggested that their role title wouldn't necessarily have the specialty in the title .

**Comment by rbanks54** [comment]
> What if you are a very very good generalist?

@robdmoore Then you'll be a very, very good Senior Developer. I know it's the Readify way, but let's resist the urge to fork the discussion about the SE role into one about defining levels of awesome within existing roles. I'd suggest that's a discussion you should have with our People Director :-)

**Comment by dimitar** [comment]
This might just be me, but I think its important that an SE invests in fields rather than technologies, so Cloud over Azure or Web over MVC. Thoughts?

**Comment by rbanks54** [comment]
@dimitar I didn't want to be too prescriptive about that as no one knows how the field may change in the future. I tried to keep it generic with this statement `"I am able to talk confidently about alternative solutions in my specialisation area."`

For example, if I know Angular inside and out, but I can't talk about React/Polymer/Ember/Knockout/ShinyNewFramework then I've got a gap that needs filling.

Maybe it needs better wording or needs to be moved to a different section?

**Comment by feelingweird** [comment]
Is the SE role now replacing the Technical specialist role (i.e. are we taking TS away from consultants). The reason i ask is that a fair few of the points listed come from the technical specialist role. 

I *thought* the role was about people who didn't want to be consultants. Who maybe don't want to speak at conferences, or are not that comfortable in-front of a crowd, and the second paragraph is about getting your name out, and the first set of values attributed to the role really speak to me as if this is a consulting role.  
`I am the go-to person in my technology area and am known outside of Readify for it.`
Why is technical brilliance tied to being a speaker/blogger? 

I believe Readify is big enough that not every consultant (or other title) needs to be a walking ad/brand for Readify. So what is the justification for this requirement of the role?

**Comment by aaronpowell** [comment]
@feelingweird TS was never really a role, it was more an award, so (speaking as a TS) I don't see the SE role as taking anything away.

> So what is the justification for this requirement of the role?

The kind of person I see in a SE role is a leader (in a technical sense) both inside and outside the organisation. It's not just someone who is knows a technology but is also passionate about it, which is why the blogging/speaking is important. An SE isn't a SD who's _don't **X** for a while_ but someone who is passionate about **X**.

**Comment by feelingweird** [comment]
@aaronpowell Sorry, my mistake. I knew TS was an award, and not an award to only SCs, as some SDs have it too. I remember reading a blog post about what @robdmoore did to get his TS award. Impressive!!

I feel like the blogging/speaking is a way of measuring someones knowledge rather than passion. Passion i would argue can be expressed in many ways depending on the type of person. I see the speaking/blogging side of things as a left over of 'its in a book, it must be true'. If they are out there speaking, then they must know about the field/tech etc. 

So if its a measurement of passion and knowledge then is there not other ways to measure these traits?

So what do people see as the differences between the TS award and the SE role?

**Comment by rbanks54** [comment]
@feelingweird The SE role requires knowledge, passion, and awesome practical abilities. It also needs a willingness to share knowledge and passion with others. An SE is our "best of the best, deepest of the deep" technical role and should reflect our ideals of "Discover, Master, Influence". Personally I don't want people being an SE if I can't look at them with a measure of respect and awe. I don't want people to be SEs simply because they're pretty good but largely invisible.

To quote the line you're referring to: _This **may** include speaking at conferences and user groups, writing books or blog posts, answering StackOverflow or forum questions, being an MVP or more_

So does that mean if they aren't blogging they can't be an SE? No. But they do need to be `known for [their] deep knowledge in [their] area(s) of specialisation`.  If they are invisible, how do they become known as an expert in that field/area? If they can show that in a way that doesn't involve books/blogs/forums or otherwise, that's great.

If someone can tick all the other items bar that one, that's not a problem. There's no reason they can't be an SE. They just have a gap that they can work on in their PD plan.

**Comment by RaphHaddad** [comment]
An SE must be 

known/acknowledged/recognised as being highly proficient in a certain 'area' of specialty and not necessarily a technology. For example: Mobile and not Xamarin. Or Delivery and not Octopus Deploy.

In terms of the spectrum on 'Discover', 'Master', 'Influence'. I would say an SE would be sitting between 'master' and 'influence'. An LE would be at an 'influence' level and a PE would simply be the industry leader.

I feel the above discussion is putting the SE role all the way up to the 'influence' level and thus would making the description for LE and PE far more difficult. 

Just my 2c.

**Comment by dimitar** [comment]
I'd like to commit this so we have a baseline to start iterating over, Any objections?

**Comment by robdmoore** [comment]
Yolo

--
Rob Moore | Readify Principal Consultant, Technical Specialist (Microsoft Azure) | m +61 400 777 763 | e rob.moore@readify.net | w readify.net

**Comment by aaronpowell** [comment]
@dimitar - let's set a timebox for responses, say COB AEST Monday

**Comment by aaronpowell** [comment]
**Unless there are objections I will merge this 3rd August.**

**Pull request merged**
