### PR TITLE
'Agile' MadSkill distinction between SD, SC and LC

### PR DESCRIPTION
**Pull request by RaphHaddad**
Doing my retros I've found that 'I am proficient at delivering software projects using agile practices.' is ambiguous. I'm wondering if we can have a discussion on how to clarify agile MadSkillz in a way that we can more clearly define the responsibilities of an SD, SC, LC.

### CODE REVIEW

**Comment by mishrsud** [comment]
LGTM 👍

**Comment by andrewabest** [comment]
@RaphHaddad I don't know how many of our LC's are leading multiple teams on engagements - I agree that knowing how Scrum / etc scale in multi-team scenarios is handy, but I'm not entirely sure that claiming LCs should be 'proficient' in it is entirely accurate.

**Comment by RaphHaddad** [comment]
@andrewabest to answer your question - I am not sure. But I do know that LCs regularly lead larger teams 7-9+.

However, I do feel that the expectation of an SD, SC and LC should be different when leading agile teams. At the moment, MadSkillz does not reflect this. 

The way I see it. 
GD - should be learning about agile and agile methodologies by learning from others. 
D - should now be learning about agile methodologies through their own experiences and others.
SD - should be a proficient agile practitioner (but still learning)
SC - should be able to lead small teams (3-5) using agile delivery (but still learning)
LC - should be able to scale agile practices to larger teams (7-9+) (and obviously still learning)

If the above expectations are true (not sure who actually validates them) then there should be a distinction on MadSkillz.

**Comment by todthomson** [comment]
@RaphHaddad how about something like:

> I have a track record of delivering successful projects by applying agile practices when leading teams.

**Comment by RaphHaddad** [comment]
@todthomson what would you make the SC, SD, D and GD MadSkill?

**Comment by andrewabest** [comment]
@RaphHaddad I feel this one just needs a little more love to get it over the line :) It is close!
GD - I am aware of agile practices, and am actively learning how to apply them day to day
D - I am applying agile practices in my day to day work, and beginning to understand why they are important to software development
I think your SD and SC changes are good, and then use @todthomson's suggestion for LC.

Thoughts?

**Comment by RaphHaddad** [comment]
Sounds good. I will try to modify the PR but am not around the country. If someone else can beat me too it we could probably get this merged earlier.

**Comment by andrewabest** [comment]
@RaphHaddad are you back in the country now? ;)

**Comment by RaphHaddad** [comment]
🇦🇺 Yes you're right @andrewabest :) I will do this soon 🇦🇺

**Pull request merged**
