### PR TITLE
Focusing on technical excellence as opposed to comparison with SD role

### PR DESCRIPTION
**Pull request by MehdiK**
> I am more than a Senior Developer

This is not the right language. No one is more than others in such a blanket statement way.

### CODE REVIEW

**Comment by MehdiK** [comment]
I feel that `I am known for my technical knowledge` heading covers the moved points well. Perhaps we can change that to `I am a thought leader in technology and architecture`?

**Comment by robdmoore** [comment]
Maybe “I am maturing as a thought leader in technology and architecture”? Gives space for growth in LE

--


On 29 May 2018, at 6:41 am, Mehdi Khalili <notifications@github.com<mailto:notifications@github.com>> wrote:


I feel that I am known for my technical knowledge heading covers the moved points well. Perhaps we can change that to I am a thought leader in technology and architecture?

**Comment by AdrianJSClark** [comment]
Pretty sure that phrase was there to try and separate the Senior Engineer from the Senior Developer role. Looking at the Senior Developer role, the "I am trusted to ship full products (or vertical slices of larger products) from idea to production." section is kind of the pre-cursor to the attributes of the section being renamed. I say this because they're all about building and providing a solution to a customer's problem, rather than either communicating with the customer or improving yourself or your team through learning.

Keeping this in mind I thought something that spoke more towards delivery of a solution would be a suitable replacement header. My attempt at this is below, although many of the other suggestions here are OK.

*I can plan and implement solutions which include resolutions for very difficult technical problems and handling challenging environments.*

**Comment by MehdiK** [comment]
Have a look now. I added a new heading. I like @robdmoore's suggestion.

**Comment by andrewabest** [comment]
@MehdiK are we going to tackle this one in the same PR?

> I have the skills, speed and knowledge that enable me to consistently be one of the most productive team members of any team I am part of.

**Comment by MehdiK** [comment]
Different PR. Waiting for this to be merged first @andrewabest

**Pull request merged**
