### PR TITLE
Update Readme with levelling up changes

### PR DESCRIPTION
**Pull request by andrewabest**
As per the discussion in https://github.com/Readify/madskillz/issues/34

### CODE REVIEW

**Comment by bendetat** [comment]
I would add a sub-point:

`- Consider discussing this early with someone you've been working with, someone you consider a mentor, or someone you want to get constructive feedback from, so that they can help provide feedback on your goals`

I think the mentoring aspect is pretty important in mad skillz.

**Comment by andrewabest** [comment]
@bendetat @aaronpowell given @tathamoddie's comment https://github.com/Readify/madskillz/issues/34#issuecomment-113994778 perhaps we are best editing https://readify.sharepoint.com/the-way-we-work/Pages/Retro.aspx and updating that with some additional information?

**Comment by bendetat** [comment]
the day sharepoint supports pull requests is the day I would be slightly less sad about that suggestion

Why not both?

**Comment by andrewabest** [comment]
@aaronpowell how about

`Consider rating yourself against both your current and future role(s) to gain an insight into what areas you can grow into`

**Comment by rbanks54** [comment]
I'd try this:

```
If you're aiming for a promotion, rate yourself on both your current role and your desired role.
Looking at the desired role will provide clarity about gaps you might need to fill or grow into.
```

**Comment by andrewabest** [comment]
I like it @rbanks54. Going to add that along with a slightly trimmed version of @bendetat's suggestion.

**Pull request merged**
