### PR TITLE
Devs should be writing the correct code

### PR DESCRIPTION
**Pull request by bendetat**
This pivots into some 'soft skills' but none of us should be working in a vacuum.

### CODE REVIEW

**Comment by aaronpowell** [comment]
Maybe I'm missing something here, this seems like it should be a given and not something that needs to be spelt out.

**Comment by bendetat** [comment]
IKR ;-)

But I just got questioned on why I assumed that was already part of "I write high quality code quickly and ship it to production", as part of somebody's PD goal. So here we are.

**Comment by robdmoore** [comment]
Seems obvious, but happy for it to be included

**Comment by rbanks54** [comment]
I'm merging it on the proviso that we don't progress from here to items such as "I compile my code before committing it" or other items that are best left as part of a team's Definition of Done :-)

**Pull request merged**
