### PR TITLE
Clarify and expand on "richer for the experience" in SC role

### PR DESCRIPTION
**Pull request by WillRay**
Address the issue raised by Meligy #53 about the wording for this line. I've expanded it to address "difficult conversations" in general, beyond just challenging others.

### CODE REVIEW

**Comment by ghuntley** [comment]
re: tact

http://www.mit.edu/~jcb/tact.html

**Comment by andrewabest** [comment]
Looks good @WillRay - just one comment.

I'd change

> I can effectively coach people and pass on meaningful knowledge

to

> I can effectively coach people and pass on my knowledge

To avoid any ambiguity around the meaning of meaningful 😉

**Comment by WillRay** [comment]
@andrewabest Sounds good. To be honest, the second part of the sentence seems a bit redundant now. What about "I can effectively pass on my knowledge to people." Is there a need for it to be explicit as far as "coaching" is concerned? This could potentially apply to documentation then, too.

**Comment by andrewabest** [comment]
@WillRay I don't think we want to be too general here - this isn't about documentation, it is specifically about coaching other developers - whether they be Readify devs or members of our client's teams.

**Comment by random82** [comment]
:shipit:

**Pull request merged**
