### PR TITLE
Maturing / need coaching

### PR DESCRIPTION
**Pull request by random82**
Proposing changes to distinct "maturing" and "need coaching" ratings. Need coaching - needs an assistance, maturing - we're comfortable to do it on our own

### CODE REVIEW

**Comment by todthomson** [comment]
> - Maturing: _Here's some suggestions, take them or leave them - it's your call._
>   - It would make sense to record the suggestions.
>   - It looks like you're good to take suggestions on your own.

I'm not sure I follow what you mean by "It looks like you're good to take suggestions on your own"...

Maturing means "you're well on the way to 'no brainer', you're just not there yet" and "here are some suggestions of skills and behaviours that you could deliberately try to adopt which I feel would get you to no brainer - take them or leave them, it's your call".

> - Needs coaching: _This is an area you're weak in, let's work out a plan and walk this out together._
>   - It would make sense to record the coaching plan.
>   - You might need some assistance in that space.

Isn't the "let's work out a plan and walk this out together" the plan to provide some assistance in that space?

Apologies, struggling to see what extra value these extra lines provide and less is more IMHO.

Perhaps some clarification to these lines is all that is needed to make their contribution(s) clear?

**Comment by random82** [comment]
I don't see such a clear cut and have a recent experience when it was confusing to another person as well.
I'm proposing to clarify it, not to change it.

**Comment by todthomson** [comment]
> I'm proposing to clarify it, not to change it.

I'm all for clarifying it. :+1: 

My point above is that these additional lines serve the opposite purpose.

> I don't see such a clear cut and have a recent experience when it was confusing to another person as well.

**Comment by todthomson** [comment]
Same confusion on my end w.r.t. "You might need some assistance in that space".

If I rate someone "needs coaching" or they rate themselves "needs coaching" and after discussions (getting on the same page) the rating remains "needs coaching" I'm going to formulate a coaching plan (step 1 === find a coach) for them then and there.

I'm trying not to leave them with "You might need some assistance in that space" as it's too vague. My plan is to "work out a plan and walk this out together" and "record the coaching plan" which will be a concrete list of specific steps the person/coach can undertake to get them going on the "maturing" road.

"You might need some assistance in that space" is just too general and vague for my liking is all.

**Comment by random82** [comment]
Makes sense, do you want to prose changes in this branch?

**Comment by todthomson** [comment]
> Makes sense, do you want to prose changes in this branch?

**Comment by andrewabest** [comment]
@todthomson any movement on this one? 

I'm not entirely sure where the confusion is - Madskillz deliberately simplified the ratings so that we are either awesome, great but have things we could sharpen, or either 'not great' or just beginning, so need a fair bit of structured work to bring up.

I feel we could refine the statement next to the rating name, but don't think extra line items below it add value.

**Comment by andrewabest** [comment]
The suggested additions can already be interpreted from the parent items, and add little value. I'm going to close this one. 

@random82 if you'd like to continue the discussion on the ratings - perhaps we could talk in an issue to try and come to a consensus?

**Pull request closed without merging**
