### PR TITLE
add MIT license to madskillz

### PR DESCRIPTION
**Pull request by ghuntley**
🙇‍♀️

### CODE REVIEW

**Comment by todthomson** [comment]
Up until this point Mad Skillz has had no licence, so an explicit licence for Mad Skillz would be a good thing (I think).

That being said, I feel that this licence is worth considering:
https://creativecommons.org/licenses/by-sa/4.0/

**Comment by MattDavies** [comment]
Agree with @todthomson. I'd prefer CC over MIT in this instance.

Were you looking to add this in for any particular purpose @ghuntley, or just filling the gap?

**Comment by todthomson** [comment]
I'm open to MIT (or any licence).

As you say @MattDavies let's hear from @ghuntley as to why he's suggesting MIT... He probably has a good reason.

**Comment by ghuntley** [comment]
I'm sitting at my desk writing up behaviours and I'm like _this already exists_. So let's add clarify that madskills is indeed open-source.

https://creativecommons.org/licenses/by-sa/4.0/ is great. It was either cc-sa40 or mit. I rolled the dice and chose MIT.

Do you want me to rework the PR with by-sa?

**Comment by MattDavies** [comment]
Yep, happy with that.

**Comment by ghuntley** [comment]
Closing this out, head on over to 🚢  https://github.com/Readify/madskillz/pull/116 please.

**Pull request closed without merging**
