### PR TITLE
Remove risk line

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
>I am comfortable diving head-first into moderately risky environments with relatively little upfront information and oversight.

This, to me suggests that we are not planning our work with clients appropriately before sending out consultants. I suggest we remove it and also establish a working practise that doesn't allow this situation (accepting edge cases). If a team is to be sent out to a client then they should be involved much earlier in any delivery processes (scoping, design etc) to ensure that everyone is is up to speed.

### CODE REVIEW

**Comment by AdrianJSClark** [comment]
I personally think Senior Consultants **do** need the ability to manage a risky environment with little information upfront. The fact you have indicated there are edge cases identifies for me the need to consider this skill when promoting or hiring an SC.

However I agree that Sales, Pre-Sales, and Delivery Manager/PCs should do all they can to ensure those skills are not regularly put to the test.

**Comment by JimBobSquarePants** [comment]
Then it requires rephrasing to indicate that this should be an edge case. Otherwise it's off putting.

**Comment by robdmoore** [comment]
The reality is that we are a consulting company. We aren't usually engaged by a client because everything is peachy and there will always be a bunch of risks they need to be mitigated on day 1.

A lot of the time, experienced senior consultants will be given a lot of autonomy (little oversight) and be expected to call out when they need help.

Also, while the presales team should collect and provide as much information as possible to prep consultants most of the time when we walk in on day 1 reality is different from pre sales. That's why we have techniques like the kick off deck (check out Readdit > Field Guide > Delivery) to get it started right.

Personally I think the statement is ok, but happy to talk through what aspects of it concern you about it so we can improve it? :)


On 15 Feb 2017, at 6:13 am, James Jackson-South <notifications@github.com<mailto:notifications@github.com>> wrote:


I am comfortable diving head-first into moderately risky environments with relatively little upfront information and oversight.

This, to me suggests that we are not planning our work with clients appropriately before sending out consultants. I suggest we remove it and also establish a working practise that doesn't allow this situation (accepting edge cases). If a team is to be sent out to a client then they should be involved much earlier in any delivery processes (scoping, design etc) to ensure that everyone is is up to speed.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Readify/madskillz/pull/81<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FReadify%2Fmadskillz%2Fpull%2F81&data=01%7C01%7Crob.moore%40readify.net%7Cac3b72ba2f354339d6e908d45526af8e%7C413504eb862247d2aa72ddbba4584471%7C0&sdata=iz72X5Rwh6B3Ufv5x5JURgJ5qC1GblZmalyyth4Ejr0%3D&reserved=0>

Commit Summary

  *   Remove risk line

File Changes

  *   M Consulting.md<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FReadify%2Fmadskillz%2Fpull%2F81%2Ffiles%23diff-0&data=01%7C01%7Crob.moore%40readify.net%7Cac3b72ba2f354339d6e908d45526af8e%7C413504eb862247d2aa72ddbba4584471%7C0&sdata=LcDLg%2Fg943Igo0bzP%2Br8hi5cstaVf%2FLZ2dK52qvsAOo%3D&reserved=0> (1)

Patch Links:

  *   https://github.com/Readify/madskillz/pull/81.patch<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FReadify%2Fmadskillz%2Fpull%2F81.patch&data=01%7C01%7Crob.moore%40readify.net%7Cac3b72ba2f354339d6e908d45526af8e%7C413504eb862247d2aa72ddbba4584471%7C0&sdata=H0A68DE0MzSSyCs%2Fu3JlRxc4L4YCc8MmgABz0hu66iQ%3D&reserved=0>
  *   https://github.com/Readify/madskillz/pull/81.diff<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FReadify%2Fmadskillz%2Fpull%2F81.diff&data=01%7C01%7Crob.moore%40readify.net%7Cac3b72ba2f354339d6e908d45526af8e%7C413504eb862247d2aa72ddbba4584471%7C0&sdata=9uGksWd0Vss3dzx1bFzr1OCISxZ%2FLoimTMzmEQcePcY%3D&reserved=0>

**Comment by JimBobSquarePants** [comment]
😄 Thanks @robdmoore Not trying to rock the boat or anything I just want to make the way it reads either more friendly or remove it. I read it again today and my first thought was "Whoa!" as to me it read like this would be a common occurrence.

Now that we've established that it is an edge case I suggest that it should be slightly altered

>I am comfortable, _in extreme circumstance_, navigating moderately risky environments with relatively little upfront information and oversight.

I replaced "diving head-first" also as that read, to me, like a reckless response.

I can close this and open another issue/PR if you like?

**Comment by robdmoore** [comment]
Context: James and I had a chat privately about upfront information from presales given to consultants and various support channels we have as well as the normal reality of projects in risky environments (which this statement covers). We agreed to revisit this again in the future once James has more time to think about how we can make the statement clearer :)

(Thanks for the PR and chat buddy - always good to talk through this stuff!)

**Pull request closed without merging**
