### PR TITLE
Delivery manager

### PR DESCRIPTION
**Pull request by stephengodbold**
Introducing some thinking around the DM role, and how it is shaped within the business. 

The intent of inclusion here is to help to define the skills and behaviors aspects of the role collaboratively within the DM group, as well as in the open with the rest of the team.

### CODE REVIEW

**Comment by aaronpowell** [comment]
Where would be the entry point to this? Currently on the [ReadMe](https://github.com/Readify/madskillz/blob/master/README.md) we have a link to the Consulting Roles and Managed Services roles. Does it link from within that list or is it a branch from a point within one of the existing roles?

**Comment by stephengodbold** [comment]
A new type, similar to the existing links. I don't think it's necessary to branch from any of the current roles.

**Comment by robdmoore** [comment]
Looks like a great start - nice one

**Comment by dimitar** [comment]
:+1: Looks good!

**Comment by RaphHaddad** [comment]
should we merge this?

**Comment by stephengodbold** [comment]
I'd like to wait until we hear from the other DM's before we merge I think.

**Pull request merged**
